INSERT INTO dtb_order (
    customer_id,
    payment_id,
    pre_order_id,
    order_no,
    name01,
    name02,
    subtotal,
    discount,
    delivery_fee_total,
    charge,
    tax,
    total,
    payment_total,
    add_point,
    use_point,
    order_status_id,
    order_date,
    payment_date,
    create_date,
    update_date,
    discriminator_type
)
SELECT CASE
           WHEN JSON_VALUE(CAST(:order AS JSON), '$.customerId') REGEXP '^[0-9]+$'
               THEN CAST(JSON_VALUE(CAST(:order AS JSON), '$.customerId') AS UNSIGNED)
           ELSE NULL
       END,
       NULLIF(CAST(JSON_VALUE(CAST(:order AS JSON), '$.paymentMethodId') AS SIGNED), 0),
       NULLIF(JSON_VALUE(CAST(:order AS JSON), '$.preOrderId'), ''),
       JSON_VALUE(CAST(:order AS JSON), '$.orderNo'),
       '-',
       '-',
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.subtotal') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.discount') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.deliveryFeeTotal') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.charge') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.tax') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.total') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.paymentTotal') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.addPoint') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.usePoint') AS SIGNED),
       CAST(JSON_VALUE(CAST(:order AS JSON), '$.orderStatus') AS SIGNED),
       NULLIF(REPLACE(JSON_VALUE(CAST(:order AS JSON), '$.orderDate'), 'T', ' '), ''),
       NULLIF(REPLACE(JSON_VALUE(CAST(:order AS JSON), '$.paymentDate'), 'T', ' '), ''),
       NOW(),
       NOW(),
       'order'
ON DUPLICATE KEY UPDATE
    order_no = VALUES(order_no),
    customer_id = VALUES(customer_id),
    payment_id = VALUES(payment_id),
    subtotal = VALUES(subtotal),
    discount = VALUES(discount),
    delivery_fee_total = VALUES(delivery_fee_total),
    charge = VALUES(charge),
    tax = VALUES(tax),
    total = VALUES(total),
    payment_total = VALUES(payment_total),
    add_point = VALUES(add_point),
    use_point = VALUES(use_point),
    order_status_id = VALUES(order_status_id),
    order_date = VALUES(order_date),
    payment_date = VALUES(payment_date),
    update_date = NOW()
