#!/usr/bin/env python3
"""Materialise the Be Framework fake fixtures (be/var/fake/*.json) into a
relation-consistent SQL seed for the dev/SQL context.

The fake fixtures are domain-shaped and NOT internally FK-consistent (built for
the no-FK FakeQuery world). This generator reuses their *values* (product names,
prices, customer emails …) but emits a consistent dataset: categories derived
from product.categoryNames, product → class → stock → image → category/tag links,
and loginnable customers. Output: sql/seed/dev-fixture.sql (idempotent-ish; meant
to run on a freshly setup-db.sh'd database).
"""
import json
from pathlib import Path

FAKE = Path(__file__).resolve().parents[2] / "be" / "var" / "fake"
OUT = Path(__file__).resolve().parent / "dev-fixture.sql"

def load(name):
    p = FAKE / f"{name}.json"
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else []

products = load("products")
pclasses = load("product_classes")
customers = load("customers")

def sq(v):
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("\\", "\\\\").replace("'", "''") + "'"

# class detail per productCode (first match)
cls_by_code = {}
for c in pclasses:
    cls_by_code.setdefault(c["productCode"], c)

# derive categories + tags from products
cat_names, tag_names = [], []
for p in products:
    for n in (p.get("categoryNames") or []):
        if n not in cat_names:
            cat_names.append(n)
    for n in (p.get("tagNames") or []):
        if n not in tag_names:
            tag_names.append(n)
cat_id = {n: i + 1 for i, n in enumerate(cat_names)}
tag_id = {n: i + 1 for i, n in enumerate(tag_names)}

L = ["-- generated by sql/seed/build-dev-fixture.py from be/var/fake/*.json",
     "SET FOREIGN_KEY_CHECKS=0;",
     "DELETE FROM dtb_product_tag; DELETE FROM dtb_product_category; DELETE FROM dtb_product_image;",
     "DELETE FROM dtb_product_stock; DELETE FROM dtb_product_class; DELETE FROM dtb_product;",
     "DELETE FROM dtb_tag; DELETE FROM dtb_category;",
     "DELETE FROM dtb_shipping; DELETE FROM dtb_order_item; DELETE FROM dtb_order;",
     "DELETE FROM dtb_customer WHERE email LIKE '%@example.com';"]

NOW = "NOW()"
for n, i in cat_id.items():
    L.append(f"INSERT INTO dtb_category (id, category_name, hierarchy, sort_no, create_date, update_date, discriminator_type) "
             f"VALUES ({i}, {sq(n)}, 1, {i}, {NOW}, {NOW}, 'category');")
for n, i in tag_id.items():
    L.append(f"INSERT INTO dtb_tag (id, name, sort_no, discriminator_type) VALUES ({i}, {sq(n)}, {i}, 'tag');")

pid = 0
pcid = 0
code_to_pid = {}
code_to_name = {}
for p in products:
    pid += 1
    code = p["productCode"]
    code_to_pid[code] = pid
    code_to_name[code] = p["productName"]
    c = cls_by_code.get(code, {})
    L.append(f"INSERT INTO dtb_product (id, name, product_status_id, description_detail, search_word, note, create_date, update_date, discriminator_type) "
             f"VALUES ({pid}, {sq(p['productName'])}, {sq(p.get('productStatus') or 1)}, {sq(p.get('description'))}, {sq(p.get('searchWord'))}, {sq(p.get('note'))}, {NOW}, {NOW}, 'product');")
    pcid += 1
    stock = p.get("stock")
    unlimited = 1 if (c.get("stockUnlimited") or stock is None) else 0
    L.append(f"INSERT INTO dtb_product_class (id, product_id, product_code, price01, price02, stock, stock_unlimited, sale_type_id, visible, create_date, update_date, discriminator_type) "
             f"VALUES ({pcid}, {pid}, {sq(code)}, {sq(c.get('price01'))}, {sq(p.get('price02') or c.get('price02') or 0)}, {sq(stock)}, {unlimited}, {sq(c.get('saleTypeId') or 1)}, 1, {NOW}, {NOW}, 'product_class');")
    L.append(f"INSERT INTO dtb_product_stock (id, product_class_id, stock, create_date, update_date, discriminator_type) "
             f"VALUES ({pcid}, {pcid}, {sq(stock)}, {NOW}, {NOW}, 'product_stock');")
    if p.get("imagePath"):
        L.append(f"INSERT INTO dtb_product_image (id, product_id, file_name, sort_no, create_date, discriminator_type) "
                 f"VALUES ({pid}, {pid}, {sq(p['imagePath'])}, 0, {NOW}, 'product_image');")
    for cn in (p.get("categoryNames") or []):
        L.append(f"INSERT INTO dtb_product_category (product_id, category_id, discriminator_type) VALUES ({pid}, {cat_id[cn]}, 'product_category');")
    for tn in (p.get("tagNames") or []):
        L.append(f"INSERT INTO dtb_product_tag (product_id, tag_id, create_date, discriminator_type) VALUES ({pid}, {tag_id[tn]}, {NOW}, 'product_tag');")

cid = 0
for cu in customers:
    cid += 1
    L.append(f"INSERT INTO dtb_customer (id, name01, name02, kana01, kana02, company_name, email, password, salt, secret_key, phone_number, postal_code, pref_id, addr01, addr02, birth, sex_id, job_id, point, customer_status_id, create_date, update_date, discriminator_type) "
             f"VALUES ({cid}, {sq(cu.get('name01'))}, {sq(cu.get('name02'))}, {sq(cu.get('kana01'))}, {sq(cu.get('kana02'))}, {sq(cu.get('companyName'))}, {sq(cu['email'])}, {sq(cu['passwordHash'])}, NULL, {sq('secret-'+str(cid))}, {sq(cu.get('phoneNumber'))}, {sq(cu.get('postalCode'))}, {sq(cu.get('pref'))}, {sq(cu.get('addr01'))}, {sq(cu.get('addr02'))}, {sq(cu.get('birth'))}, {sq(cu.get('sex'))}, {sq(cu.get('job'))}, {sq(cu.get('initialPoint') or 0)}, {sq(cu.get('customerStatus') or 2)}, {NOW}, {NOW}, 'customer');")
# orders — fake order intents are not FK-consistent, so link them to seeded
# customers (round-robin) and resolve item productCodes to seeded products.
orders = load("orders")
cust_ids = list(range(1, cid + 1)) or [1]
oid = 0
oiid = 0
for o in orders:
    oid += 1
    customer_id = cust_ids[(oid - 1) % len(cust_ids)]
    items = o.get("items") or []
    total = sum((it.get("price") or 0) * (it.get("quantity") or 0) for it in items) + (o.get("deliveryFeeTotal") or 0)
    order_no = (o.get("preOrderId") or f"order-{oid}")[:24]
    status = [1, 6][(oid - 1) % 2]
    L.append(f"INSERT INTO dtb_order (id, customer_id, order_no, order_status_id, order_date, name01, name02, payment_total, create_date, update_date, discriminator_type) "
             f"VALUES ({oid}, {customer_id}, {sq(order_no)}, {status}, {NOW}, '注文', '太郎', {sq(total)}, {NOW}, {NOW}, 'order');")
    for it in items:
        oiid += 1
        icode = it.get("productCode")
        L.append(f"INSERT INTO dtb_order_item (id, order_id, product_id, product_code, product_name, quantity, price, order_item_type_id, discriminator_type) "
                 f"VALUES ({oiid}, {oid}, {sq(code_to_pid.get(icode))}, {sq(icode)}, {sq(code_to_name.get(icode) or icode or 'item')}, {sq(it.get('quantity'))}, {sq(it.get('price'))}, 1, 'order_item');")
    L.append(f"INSERT INTO dtb_shipping (id, order_id, name01, name02, postal_code, pref_id, addr01, addr02, phone_number, create_date, update_date, discriminator_type) "
             f"VALUES ({oid}, {oid}, '注文', '太郎', '1500001', 13, '渋谷区', 'テスト1-1-1', '0312345678', {NOW}, {NOW}, 'shipping');")
L.append("SET FOREIGN_KEY_CHECKS=1;")
OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"wrote {OUT}  (categories={len(cat_id)} tags={len(tag_id)} products={pid} customers={cid})")
