-- sql/seed/mtb-master.sql
--
-- EC-CUBE 4.3 master/reference data for all 22 mtb_* tables.
-- Extracted from EC-CUBE 4.3's installer fixtures:
--   src/Eccube/Resource/doctrine/import_csv/ja/mtb_*.csv
-- (the same CSVs LoadDataFixturesEccubeCommand / the installer load).
--
-- Reference data only: prefectures, order statuses, sale types, sexes,
-- jobs, csv types, authorities, countries, work flags, etc. No PII.
--
-- Idempotent: each table is TRUNCATEd then re-INSERTed, so re-running
-- this file restores the canonical master rows. FK checks are disabled
-- for the duration (mtb_* rows are referenced by dtb_* tables).
--
-- Generated by sql/setup-db.sh tooling; do not hand-edit — regenerate
-- from the EC-CUBE source CSVs instead.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- mtb_authority (2 rows)
TRUNCATE TABLE `mtb_authority`;
INSERT INTO `mtb_authority` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(0, 'システム管理者', 0, 'authority'),
(1, '店舗オーナー', 1, 'authority');

-- mtb_country (249 rows)
TRUNCATE TABLE `mtb_country`;
INSERT INTO `mtb_country` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(352, 'アイスランド', 1, 'country'),
(372, 'アイルランド', 2, 'country'),
(31, 'アゼルバイジャン', 3, 'country'),
(4, 'アフガニスタン', 4, 'country'),
(840, 'アメリカ合衆国', 5, 'country'),
(850, 'アメリカ領ヴァージン諸島', 6, 'country'),
(16, 'アメリカ領サモア', 7, 'country'),
(784, 'アラブ首長国連邦', 8, 'country'),
(12, 'アルジェリア', 9, 'country'),
(32, 'アルゼンチン', 10, 'country'),
(533, 'アルバ', 11, 'country'),
(8, 'アルバニア', 12, 'country'),
(51, 'アルメニア', 13, 'country'),
(660, 'アンギラ', 14, 'country'),
(24, 'アンゴラ', 15, 'country'),
(28, 'アンティグア・バーブーダ', 16, 'country'),
(20, 'アンドラ', 17, 'country'),
(887, 'イエメン', 18, 'country'),
(826, 'イギリス', 19, 'country'),
(86, 'イギリス領インド洋地域', 20, 'country'),
(92, 'イギリス領ヴァージン諸島', 21, 'country'),
(376, 'イスラエル', 22, 'country'),
(380, 'イタリア', 23, 'country'),
(368, 'イラク', 24, 'country'),
(364, 'イラン|イラン・イスラム共和国', 25, 'country'),
(356, 'インド', 26, 'country'),
(360, 'インドネシア', 27, 'country'),
(876, 'ウォリス・フツナ', 28, 'country'),
(800, 'ウガンダ', 29, 'country'),
(804, 'ウクライナ', 30, 'country'),
(860, 'ウズベキスタン', 31, 'country'),
(858, 'ウルグアイ', 32, 'country'),
(218, 'エクアドル', 33, 'country'),
(818, 'エジプト', 34, 'country'),
(233, 'エストニア', 35, 'country'),
(231, 'エチオピア', 36, 'country'),
(232, 'エリトリア', 37, 'country'),
(222, 'エルサルバドル', 38, 'country'),
(36, 'オーストラリア', 39, 'country'),
(40, 'オーストリア', 40, 'country'),
(248, 'オーランド諸島', 41, 'country'),
(512, 'オマーン', 42, 'country'),
(528, 'オランダ', 43, 'country'),
(288, 'ガーナ', 44, 'country'),
(132, 'カーボベルデ', 45, 'country'),
(831, 'ガーンジー', 46, 'country'),
(328, 'ガイアナ', 47, 'country'),
(398, 'カザフスタン', 48, 'country'),
(634, 'カタール', 49, 'country'),
(581, '合衆国領有小離島', 50, 'country'),
(124, 'カナダ', 51, 'country'),
(266, 'ガボン', 52, 'country'),
(120, 'カメルーン', 53, 'country'),
(270, 'ガンビア', 54, 'country'),
(116, 'カンボジア', 55, 'country'),
(580, '北マリアナ諸島', 56, 'country'),
(324, 'ギニア', 57, 'country'),
(624, 'ギニアビサウ', 58, 'country'),
(196, 'キプロス', 59, 'country'),
(192, 'キューバ', 60, 'country'),
(531, 'キュラソー島|キュラソー', 61, 'country'),
(300, 'ギリシャ', 62, 'country'),
(296, 'キリバス', 63, 'country'),
(417, 'キルギス', 64, 'country'),
(320, 'グアテマラ', 65, 'country'),
(312, 'グアドループ', 66, 'country'),
(316, 'グアム', 67, 'country'),
(414, 'クウェート', 68, 'country'),
(184, 'クック諸島', 69, 'country'),
(304, 'グリーンランド', 70, 'country'),
(162, 'クリスマス島 (オーストラリア)|クリスマス島', 71, 'country'),
(268, 'グルジア', 72, 'country'),
(308, 'グレナダ', 73, 'country'),
(191, 'クロアチア', 74, 'country'),
(136, 'ケイマン諸島', 75, 'country'),
(404, 'ケニア', 76, 'country'),
(384, 'コートジボワール', 77, 'country'),
(166, 'ココス諸島|ココス（キーリング）諸島', 78, 'country'),
(188, 'コスタリカ', 79, 'country'),
(174, 'コモロ', 80, 'country'),
(170, 'コロンビア', 81, 'country'),
(178, 'コンゴ共和国', 82, 'country'),
(180, 'コンゴ民主共和国', 83, 'country'),
(682, 'サウジアラビア', 84, 'country'),
(239, 'サウスジョージア・サウスサンドウィッチ諸島', 85, 'country'),
(882, 'サモア', 86, 'country'),
(678, 'サントメ・プリンシペ', 87, 'country'),
(652, 'サン・バルテルミー島|サン・バルテルミー', 88, 'country'),
(894, 'ザンビア', 89, 'country'),
(666, 'サンピエール島・ミクロン島', 90, 'country'),
(674, 'サンマリノ', 91, 'country'),
(663, 'サン・マルタン (西インド諸島)|サン・マルタン（フランス領）', 92, 'country'),
(694, 'シエラレオネ', 93, 'country'),
(262, 'ジブチ', 94, 'country'),
(292, 'ジブラルタル', 95, 'country'),
(832, 'ジャージー', 96, 'country'),
(388, 'ジャマイカ', 97, 'country'),
(760, 'シリア|シリア・アラブ共和国', 98, 'country'),
(702, 'シンガポール', 99, 'country'),
(534, 'シント・マールテン|シント・マールテン（オランダ領）', 100, 'country'),
(716, 'ジンバブエ', 101, 'country'),
(756, 'スイス', 102, 'country'),
(752, 'スウェーデン', 103, 'country'),
(729, 'スーダン', 104, 'country'),
(744, 'スヴァールバル諸島およびヤンマイエン島', 105, 'country'),
(724, 'スペイン', 106, 'country'),
(740, 'スリナム', 107, 'country'),
(144, 'スリランカ', 108, 'country'),
(703, 'スロバキア', 109, 'country'),
(705, 'スロベニア', 110, 'country'),
(748, 'スワジランド', 111, 'country'),
(690, 'セーシェル', 112, 'country'),
(226, '赤道ギニア', 113, 'country'),
(686, 'セネガル', 114, 'country'),
(688, 'セルビア', 115, 'country'),
(659, 'セントクリストファー・ネイビス', 116, 'country'),
(670, 'セントビンセント・グレナディーン|セントビンセントおよびグレナディーン諸島', 117, 'country'),
(426, 'レソト', 246, 'country'),
(654, 'セントヘレナ・アセンションおよびトリスタンダクーニャ', 118, 'country'),
(662, 'セントルシア', 119, 'country'),
(706, 'ソマリア', 120, 'country'),
(90, 'ソロモン諸島', 121, 'country'),
(796, 'タークス・カイコス諸島', 122, 'country'),
(764, 'タイ王国|タイ', 123, 'country'),
(410, '大韓民国', 124, 'country'),
(158, '台湾', 125, 'country'),
(762, 'タジキスタン', 126, 'country'),
(834, 'タンザニア', 127, 'country'),
(203, 'チェコ', 128, 'country'),
(148, 'チャド', 129, 'country'),
(140, '中央アフリカ共和国', 130, 'country'),
(156, '中華人民共和国|中国', 131, 'country'),
(788, 'チュニジア', 132, 'country'),
(408, '朝鮮民主主義人民共和国', 133, 'country'),
(152, 'チリ', 134, 'country'),
(798, 'ツバル', 135, 'country'),
(208, 'デンマーク', 136, 'country'),
(276, 'ドイツ', 137, 'country'),
(768, 'トーゴ', 138, 'country'),
(772, 'トケラウ', 139, 'country'),
(214, 'ドミニカ共和国', 140, 'country'),
(212, 'ドミニカ国', 141, 'country'),
(780, 'トリニダード・トバゴ', 142, 'country'),
(795, 'トルクメニスタン', 143, 'country'),
(792, 'トルコ', 144, 'country'),
(776, 'トンガ', 145, 'country'),
(566, 'ナイジェリア', 146, 'country'),
(520, 'ナウル', 147, 'country'),
(516, 'ナミビア', 148, 'country'),
(10, '南極', 149, 'country'),
(570, 'ニウエ', 150, 'country'),
(558, 'ニカラグア', 151, 'country'),
(562, 'ニジェール', 152, 'country'),
(392, '日本', 153, 'country'),
(732, '西サハラ', 154, 'country'),
(540, 'ニューカレドニア', 155, 'country'),
(554, 'ニュージーランド', 156, 'country'),
(524, 'ネパール', 157, 'country'),
(574, 'ノーフォーク島', 158, 'country'),
(578, 'ノルウェー', 159, 'country'),
(334, 'ハード島とマクドナルド諸島', 160, 'country'),
(48, 'バーレーン', 161, 'country'),
(332, 'ハイチ', 162, 'country'),
(586, 'パキスタン', 163, 'country'),
(336, 'バチカン|バチカン市国', 164, 'country'),
(591, 'パナマ', 165, 'country'),
(548, 'バヌアツ', 166, 'country'),
(44, 'バハマ', 167, 'country'),
(598, 'パプアニューギニア', 168, 'country'),
(60, 'バミューダ諸島|バミューダ', 169, 'country'),
(585, 'パラオ', 170, 'country'),
(600, 'パラグアイ', 171, 'country'),
(52, 'バルバドス', 172, 'country'),
(275, 'パレスチナ', 173, 'country'),
(348, 'ハンガリー', 174, 'country'),
(50, 'バングラデシュ', 175, 'country'),
(626, '東ティモール', 176, 'country'),
(612, 'ピトケアン諸島|ピトケアン', 177, 'country'),
(242, 'フィジー', 178, 'country'),
(608, 'フィリピン', 179, 'country'),
(246, 'フィンランド', 180, 'country'),
(64, 'ブータン', 181, 'country'),
(74, 'ブーベ島', 182, 'country'),
(630, 'プエルトリコ', 183, 'country'),
(234, 'フェロー諸島', 184, 'country'),
(238, 'フォークランド諸島|フォークランド（マルビナス）諸島', 185, 'country'),
(76, 'ブラジル', 186, 'country'),
(250, 'フランス', 187, 'country'),
(254, 'フランス領ギアナ', 188, 'country'),
(258, 'フランス領ポリネシア', 189, 'country'),
(260, 'フランス領南方・南極地域', 190, 'country'),
(100, 'ブルガリア', 191, 'country'),
(854, 'ブルキナファソ', 192, 'country'),
(96, 'ブルネイ|ブルネイ・ダルサラーム', 193, 'country'),
(108, 'ブルンジ', 194, 'country'),
(704, 'ベトナム', 195, 'country'),
(204, 'ベナン', 196, 'country'),
(862, 'ベネズエラ|ベネズエラ・ボリバル共和国', 197, 'country'),
(112, 'ベラルーシ', 198, 'country'),
(84, 'ベリーズ', 199, 'country'),
(604, 'ペルー', 200, 'country'),
(56, 'ベルギー', 201, 'country'),
(616, 'ポーランド', 202, 'country'),
(70, 'ボスニア・ヘルツェゴビナ', 203, 'country'),
(72, 'ボツワナ', 204, 'country'),
(535, 'BES諸島|ボネール、シント・ユースタティウスおよびサバ', 205, 'country'),
(68, 'ボリビア|ボリビア多民族国', 206, 'country'),
(620, 'ポルトガル', 207, 'country'),
(344, '香港', 208, 'country'),
(340, 'ホンジュラス', 209, 'country'),
(584, 'マーシャル諸島', 210, 'country'),
(446, 'マカオ', 211, 'country'),
(807, 'マケドニア共和国|マケドニア旧ユーゴスラビア共和国', 212, 'country'),
(450, 'マダガスカル', 213, 'country'),
(175, 'マヨット', 214, 'country'),
(454, 'マラウイ', 215, 'country'),
(466, 'マリ共和国|マリ', 216, 'country'),
(470, 'マルタ', 217, 'country'),
(474, 'マルティニーク', 218, 'country'),
(458, 'マレーシア', 219, 'country'),
(833, 'マン島', 220, 'country'),
(583, 'ミクロネシア連邦', 221, 'country'),
(710, '南アフリカ共和国|南アフリカ', 222, 'country'),
(728, '南スーダン', 223, 'country'),
(104, 'ミャンマー', 224, 'country'),
(484, 'メキシコ', 225, 'country'),
(480, 'モーリシャス', 226, 'country'),
(478, 'モーリタニア', 227, 'country'),
(508, 'モザンビーク', 228, 'country'),
(492, 'モナコ', 229, 'country'),
(462, 'モルディブ', 230, 'country'),
(498, 'モルドバ|モルドバ共和国', 231, 'country'),
(504, 'モロッコ', 232, 'country'),
(496, 'モンゴル国|モンゴル', 233, 'country'),
(499, 'モンテネグロ', 234, 'country'),
(500, 'モントセラト', 235, 'country'),
(400, 'ヨルダン', 236, 'country'),
(418, 'ラオス|ラオス人民民主共和国', 237, 'country'),
(428, 'ラトビア', 238, 'country'),
(440, 'リトアニア', 239, 'country'),
(434, 'リビア', 240, 'country'),
(438, 'リヒテンシュタイン', 241, 'country'),
(430, 'リベリア', 242, 'country'),
(642, 'ルーマニア', 243, 'country'),
(442, 'ルクセンブルク', 244, 'country'),
(646, 'ルワンダ', 245, 'country'),
(422, 'レバノン', 247, 'country'),
(638, 'レユニオン', 248, 'country'),
(643, 'ロシア|ロシア連邦', 249, 'country');

-- mtb_csv_type (7 rows)
TRUNCATE TABLE `mtb_csv_type`;
INSERT INTO `mtb_csv_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '商品CSV', 3, 'csvtype'),
(2, '会員CSV', 4, 'csvtype'),
(3, '受注CSV', 1, 'csvtype'),
(4, '配送CSV', 1, 'csvtype'),
(5, 'カテゴリCSV', 5, 'csvtype'),
(6, '規格CSV', 6, 'csvtype'),
(7, '規格分類CSV', 7, 'csvtype');

-- mtb_customer_order_status (8 rows)
TRUNCATE TABLE `mtb_customer_order_status`;
INSERT INTO `mtb_customer_order_status` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '注文受付', 0, 'customerorderstatus'),
(3, '注文取消し', 4, 'customerorderstatus'),
(4, '注文受付', 3, 'customerorderstatus'),
(5, '発送済み', 6, 'customerorderstatus'),
(6, '注文受付', 2, 'customerorderstatus'),
(7, '注文受付', 1, 'customerorderstatus'),
(8, '注文未完了', 5, 'customerorderstatus'),
(9, '返品', 7, 'customerorderstatus');

-- mtb_customer_status (3 rows)
TRUNCATE TABLE `mtb_customer_status`;
INSERT INTO `mtb_customer_status` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '仮会員', 0, 'customerstatus'),
(2, '本会員', 1, 'customerstatus'),
(3, '退会', 2, 'customerstatus');

-- mtb_device_type (2 rows)
TRUNCATE TABLE `mtb_device_type`;
INSERT INTO `mtb_device_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(2, 'モバイル', 0, 'devicetype'),
(10, 'PC', 1, 'devicetype');

-- mtb_job (18 rows)
TRUNCATE TABLE `mtb_job`;
INSERT INTO `mtb_job` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '公務員', 0, 'job'),
(2, 'コンサルタント', 1, 'job'),
(3, 'コンピューター関連技術職', 2, 'job'),
(4, 'コンピューター関連以外の技術職', 3, 'job'),
(5, '金融関係', 4, 'job'),
(6, '医師', 5, 'job'),
(7, '弁護士', 6, 'job'),
(8, '総務・人事・事務', 7, 'job'),
(9, '営業・販売', 8, 'job'),
(10, '研究・開発', 9, 'job'),
(11, '広報・宣伝', 10, 'job'),
(12, '企画・マーケティング', 11, 'job'),
(13, 'デザイン関係', 12, 'job'),
(14, '会社経営・役員', 13, 'job'),
(15, '出版・マスコミ関係', 14, 'job'),
(16, '学生・フリーター', 15, 'job'),
(17, '主婦', 16, 'job'),
(18, 'その他', 17, 'job');

-- mtb_login_history_status (2 rows)
TRUNCATE TABLE `mtb_login_history_status`;
INSERT INTO `mtb_login_history_status` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(0, '失敗', 0, 'loginhistorystatus'),
(1, '成功', 1, 'loginhistorystatus');

-- mtb_order_item_type (6 rows)
TRUNCATE TABLE `mtb_order_item_type`;
INSERT INTO `mtb_order_item_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '商品', 0, 'orderitemtype'),
(2, '送料', 1, 'orderitemtype'),
(3, '手数料', 2, 'orderitemtype'),
(4, '割引', 3, 'orderitemtype'),
(5, '税', 4, 'orderitemtype'),
(6, 'ポイント', 5, 'orderitemtype');

-- mtb_order_status (8 rows)
TRUNCATE TABLE `mtb_order_status`;
INSERT INTO `mtb_order_status` (`id`, `name`, `sort_no`, `display_order_count`, `discriminator_type`) VALUES
(1, '新規受付', 0, 1, 'orderstatus'),
(3, '注文取消し', 3, 0, 'orderstatus'),
(4, '対応中', 2, 1, 'orderstatus'),
(5, '発送済み', 4, 0, 'orderstatus'),
(6, '入金済み', 1, 1, 'orderstatus'),
(7, '決済処理中', 6, 0, 'orderstatus'),
(8, '購入処理中', 5, 0, 'orderstatus'),
(9, '返品', 7, 0, 'orderstatus');

-- mtb_order_status_color (8 rows)
TRUNCATE TABLE `mtb_order_status_color`;
INSERT INTO `mtb_order_status_color` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '#437ec4', 0, 'orderstatuscolor'),
(3, '#C04949', 3, 'orderstatuscolor'),
(4, '#EEB128', 2, 'orderstatuscolor'),
(5, '#25B877', 4, 'orderstatuscolor'),
(6, '#25B877', 1, 'orderstatuscolor'),
(7, '#A3A3A3', 6, 'orderstatuscolor'),
(8, '#A3A3A3', 5, 'orderstatuscolor'),
(9, '#C04949', 7, 'orderstatuscolor');

-- mtb_page_max (10 rows)
TRUNCATE TABLE `mtb_page_max`;
INSERT INTO `mtb_page_max` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(10, 10, 0, 'pagemax'),
(20, 20, 1, 'pagemax'),
(30, 30, 2, 'pagemax'),
(40, 40, 3, 'pagemax'),
(50, 50, 4, 'pagemax'),
(60, 60, 5, 'pagemax'),
(70, 70, 6, 'pagemax'),
(80, 80, 7, 'pagemax'),
(90, 90, 8, 'pagemax'),
(100, 100, 9, 'pagemax');

-- mtb_pref (47 rows)
TRUNCATE TABLE `mtb_pref`;
INSERT INTO `mtb_pref` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '北海道', 1, 'pref'),
(2, '青森県', 2, 'pref'),
(3, '岩手県', 3, 'pref'),
(4, '宮城県', 4, 'pref'),
(5, '秋田県', 5, 'pref'),
(6, '山形県', 6, 'pref'),
(7, '福島県', 7, 'pref'),
(8, '茨城県', 8, 'pref'),
(9, '栃木県', 9, 'pref'),
(10, '群馬県', 10, 'pref'),
(11, '埼玉県', 11, 'pref'),
(12, '千葉県', 12, 'pref'),
(13, '東京都', 13, 'pref'),
(14, '神奈川県', 14, 'pref'),
(15, '新潟県', 15, 'pref'),
(16, '富山県', 16, 'pref'),
(17, '石川県', 17, 'pref'),
(18, '福井県', 18, 'pref'),
(19, '山梨県', 19, 'pref'),
(20, '長野県', 20, 'pref'),
(21, '岐阜県', 21, 'pref'),
(22, '静岡県', 22, 'pref'),
(23, '愛知県', 23, 'pref'),
(24, '三重県', 24, 'pref'),
(25, '滋賀県', 25, 'pref'),
(26, '京都府', 26, 'pref'),
(27, '大阪府', 27, 'pref'),
(28, '兵庫県', 28, 'pref'),
(29, '奈良県', 29, 'pref'),
(30, '和歌山県', 30, 'pref'),
(31, '鳥取県', 31, 'pref'),
(32, '島根県', 32, 'pref'),
(33, '岡山県', 33, 'pref'),
(34, '広島県', 34, 'pref'),
(35, '山口県', 35, 'pref'),
(36, '徳島県', 36, 'pref'),
(37, '香川県', 37, 'pref'),
(38, '愛媛県', 38, 'pref'),
(39, '高知県', 39, 'pref'),
(40, '福岡県', 40, 'pref'),
(41, '佐賀県', 41, 'pref'),
(42, '長崎県', 42, 'pref'),
(43, '熊本県', 43, 'pref'),
(44, '大分県', 44, 'pref'),
(45, '宮崎県', 45, 'pref'),
(46, '鹿児島県', 46, 'pref'),
(47, '沖縄県', 47, 'pref');

-- mtb_product_list_max (3 rows)
TRUNCATE TABLE `mtb_product_list_max`;
INSERT INTO `mtb_product_list_max` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(20, '20件', 0, 'productlistmax'),
(40, '40件', 1, 'productlistmax'),
(60, '60件', 2, 'productlistmax');

-- mtb_product_list_order_by (3 rows)
TRUNCATE TABLE `mtb_product_list_order_by`;
INSERT INTO `mtb_product_list_order_by` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '価格が低い順', 0, 'productlistorderby'),
(2, '新着順', 2, 'productlistorderby'),
(3, '価格が高い順', 1, 'productlistorderby');

-- mtb_product_status (3 rows)
TRUNCATE TABLE `mtb_product_status`;
INSERT INTO `mtb_product_status` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '公開', 0, 'productstatus'),
(2, '非公開', 1, 'productstatus'),
(3, '廃止', 2, 'productstatus');

-- mtb_rounding_type (3 rows)
TRUNCATE TABLE `mtb_rounding_type`;
INSERT INTO `mtb_rounding_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '四捨五入', 0, 'roundingtype'),
(2, '切り捨て', 1, 'roundingtype'),
(3, '切り上げ', 2, 'roundingtype');

-- mtb_sale_type (2 rows)
TRUNCATE TABLE `mtb_sale_type`;
INSERT INTO `mtb_sale_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '販売種別A', 0, 'saletype'),
(2, '販売種別B', 1, 'saletype');

-- mtb_sex (4 rows)
TRUNCATE TABLE `mtb_sex`;
INSERT INTO `mtb_sex` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '男性', 0, 'sex'),
(2, '女性', 1, 'sex'),
(3, 'その他', 2, 'sex'),
(4, '回答しない', 3, 'sex');

-- mtb_tax_display_type (2 rows)
TRUNCATE TABLE `mtb_tax_display_type`;
INSERT INTO `mtb_tax_display_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '税抜', 0, 'taxdisplaytype'),
(2, '税込', 1, 'taxdisplaytype');

-- mtb_tax_type (3 rows)
TRUNCATE TABLE `mtb_tax_type`;
INSERT INTO `mtb_tax_type` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(1, '課税', 0, 'taxtype'),
(2, '不課税', 1, 'taxtype'),
(3, '非課税', 2, 'taxtype');

-- mtb_work (2 rows)
TRUNCATE TABLE `mtb_work`;
INSERT INTO `mtb_work` (`id`, `name`, `sort_no`, `discriminator_type`) VALUES
(0, '非稼働', 0, 'work'),
(1, '稼働', 1, 'work');

SET FOREIGN_KEY_CHECKS = 1;
