<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Final;

use MyVendor\BeMart\Be\Exception\UnauthenticatedException;
use MyVendor\BeMart\Be\Reason\Query\CustomerQueryInterface;
use MyVendor\BeMart\Be\Reason\Service\CustomerSession;
use Ray\Di\Di\Inject;

/**
 * Mypage change-info form fetched — Final, the editable form pre-
 * populated with the logged-in customer's current values.
 *
 *   GetMypageChangeInput → MypageChangeFormFetched  (Direct, safe read)
 *
 * AUTHN: customerId comes from the session. A null session raises
 * UnauthenticatedException; a session pointing to a missing customer
 * (deleted / expired) is collapsed to the same AUTHN signal so the
 * AAA boundary doesn't leak existence — same convention `MypageFetched`
 * uses (Pilot 8 lesson).
 *
 * The `submitTo` descriptor advertises where the form posts back to
 * (Pilot 8's `Change::onPost`). Shape mirrors the simple form
 * renderers being generated by the parallel wave so the HTML
 * templates do not need a per-form dispatch.
 */
final readonly class MypageChangeFormFetched
{
    public string $customerId;
    public string $email;
    public string $name01;
    public string $name02;
    public string|null $kana01;
    public string|null $kana02;
    public string|null $companyName;
    public string|null $phoneNumber;
    public string|null $postalCode;
    public int|null $pref;
    public string|null $addr01;
    public string|null $addr02;

    /** @var array{method: string, href: string} */
    public array $submitTo;

    public function __construct(
        #[Inject] CustomerSession $session,
        #[Inject] CustomerQueryInterface $customerQuery,
    ) {
        $sessionCustomerId = $session->customerId;
        if ($sessionCustomerId === null) {
            throw new UnauthenticatedException();
        }

        $customer = $customerQuery->item($sessionCustomerId);
        if ($customer === null) {
            // Session points to a non-existent customer (deleted /
            // expired). Treat same as not-logged-in to avoid leaking
            // existence signal across the AAA boundary.
            throw new UnauthenticatedException();
        }

        $this->customerId = $customer->customerId;
        $this->email = $customer->email;
        $this->name01 = $customer->name01;
        $this->name02 = $customer->name02;
        $this->kana01 = $customer->kana01;
        $this->kana02 = $customer->kana02;
        $this->companyName = $customer->companyName;
        $this->phoneNumber = $customer->phoneNumber;
        $this->postalCode = $customer->postalCode;
        $this->pref = $customer->pref;
        $this->addr01 = $customer->addr01;
        $this->addr02 = $customer->addr02;

        $this->submitTo = [
            'method' => 'POST',
            'href' => 'page://self/mypage/change',
        ];
    }
}
