<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Address id — server-derived. Generated by
 * AddressIdGeneratorInterface (Pilot 16). Type assertion only —
 * the generator itself is the contract (opaque hex string).
 */
final class AddressId
{
    #[Validate]
    public function validate(string $addressId): void
    {
        // Type assertion only — generator is the contract.
    }
}
