<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Block id — server-derived, generated by BlockIdGeneratorInterface
 * (Wave 9).
 */
final class BlockId
{
    #[Validate]
    public function validate(string|null $blockId): void
    {
        // Type assertion only.
    }
}
