<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Category id — server-derived. Generated by
 * CategoryIdGeneratorInterface (Wave 7). Type assertion only — the
 * generator itself is the contract (opaque hex string).
 */
final class CategoryId
{
    #[Validate]
    public function validate(string|null $categoryId): void
    {
        // Type assertion only — generator is the contract.
    }
}
