<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Customer id — server-derived. Generated by
 * CustomerIdGeneratorInterface. Type assertion only — the generator
 * itself is the contract (UUID-like opaque string).
 */
final class CustomerId
{
    #[Validate]
    public function validate(string $customerId): void
    {
        // Type assertion only — generator is the contract.
    }
}
