<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Delivery master id — server-derived. Generated by
 * DeliveryIdGeneratorInterface (Wave 9θ). Type assertion only — the
 * generator is the contract.
 */
final class DeliveryId
{
    #[Validate]
    public function validate(string|null $deliveryId): void
    {
        // Type assertion only — generator is the contract.
    }
}
