<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Tag id — server-derived, generated by TagIdGeneratorInterface (Wave 9).
 */
final class TagId
{
    #[Validate]
    public function validate(string|null $tagId): void
    {
        // Type assertion only.
    }
}
