<?php

declare(strict_types=1);

namespace MyVendor\BeMart\Be\Semantic;

use Be\Framework\Attribute\Validate;

/**
 * Tax-rule master id — server-derived. Generated by
 * TaxRuleIdGeneratorInterface (Wave 9θ). Type assertion only — the
 * generator is the contract.
 */
final class TaxRuleId
{
    #[Validate]
    public function validate(string|null $taxRuleId): void
    {
        // Type assertion only — generator is the contract.
    }
}
