theme: jekyll-theme-cayman
title: BeMart
description: EC-CUBE 4.3 → BEAR.Sunday + Be Framework 移植の実証プロジェクト
url: https://be-framework.github.io
baseurl: /BeMart
repository: be-framework/BeMart
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - api/paths
